# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import upload_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=upload_app.models.user_directory_path),
        ),
    ]
