# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_auto_20170515_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='iris/<function user_directory_path at 0x0000000003E03208>'),
        ),
    ]
